image: softartdev/android-fastlane

before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - chmod +x ./gradlew
    - echo $DEFAULT_CONFIGURATION | tr ' ' '\r\n' > configuration.json
    - echo "$FIREBASE_DEV_JSON" > app/google-services.json
stages:
    - test
    - release
    - apps
    - build
    - publish

.only_merge_requests: &only_merge_requests
    only:
        refs:
            - merge_requests

.docker_image:
    tags:
        - docker
    interruptible: true
    retry: 2

.runner_tags:
    tags:
        - android-latest
    interruptible: true
    retry: 2

.testing_with_emulator:
    extends: .runner_tags
    stage: test
    retry: 2
    <<: *only_merge_requests

.release_schedule_rule: &release_schedule_rule
    rules:
        -   if: $SCHEDULED_JOB == "connectedfueling-app-release"

.empty_release_schedule_rule: &empty_release_schedule_rule
  rules:
    -   if: $SCHEDULED_JOB == "connectedfueling-app-empty-release"

.tag_rule: &tag_rule
    rules:
        -   if: $CI_COMMIT_TAG =~ /^connectedfueling-app-/

code_style:
    extends: .docker_image
    script:
        - ./gradlew clean app:ktlintCheck
    <<: *only_merge_requests

unit_test:
    extends: .docker_image
    script:
        - ./gradlew testDebugUnitTest
    <<: *only_merge_requests

android_test:
    extends: .testing_with_emulator
    script:
        - "/usr/local/share/android-sdk/tools/emulator -avd api28 > /dev/null 2>&1 -skin 480x854 -no-audio -no-boot-anim -no-snapshot -memory 2048 &"
        - "/usr/local/share/android-sdk/platform-tools/adb wait-for-device"
        - ./gradlew connectedDebugAndroidTest

pace_cloud_sdk_version_check:
    extends: .docker_image
    retry: 0
    script:
        - export PACE_CLOUD_SDK_VERSION=$(grep -m 1 "cloud.pace:sdk" app/build.gradle.kts | cut -d':' -f 3 | cut -d'"' -f 1)
        - "echo PACE Cloud SDK version: $PACE_CLOUD_SDK_VERSION"
        - >
            if [[ "$PACE_CLOUD_SDK_VERSION" == *-SNAPSHOT* ]]; then
              echo "Please use a stable PACE Cloud SDK version before merging. Snapshot versions are only allowed during development."
              exit 1
            else
              echo "The PACE Cloud SDK version is already a stable version. No adjustments needed."
              exit 0
            fi
    <<: *only_merge_requests

trigger_github_mirroring:
    interruptible: true
    script:
        - ./scripts/github_mirroring.sh
    rules:
        -   if: $SCHEDULED_JOB == "connectedfueling-app-github-mirroring"

create_release:
    extends: .docker_image
    image: node:latest
    stage: release
    <<: *release_schedule_rule
    script:
        - export TAG_COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
        - echo "CI_COMMIT_SHA:" $CI_COMMIT_SHA
        - echo "Commit time to be used as build number:" $TAG_COMMIT_TIME
        - export BUILD_NUMBER=$(date -u -d @$TAG_COMMIT_TIME +"%Y%m%d%H")
        - echo "Build number:" $BUILD_NUMBER
        - export VERSION_NAME=$(date -u -d @$TAG_COMMIT_TIME +"%y.%V.%u")
        - echo "Version name:" $VERSION_NAME
        - if $(eval $CONDITION); then echo "Releasing..."; else echo "Nothing to do"; exit 0; fi
        - export CUSTOM_TAG_NAME="${TAG_PREFIX}v${VERSION_NAME}.${BUILD_NUMBER}"
        - echo "Creating tag with tag name:" $CUSTOM_TAG_NAME
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/pace/mobile/common.git tmp/common
        - cd tmp/common/scripts/release
        - yarn install
        - node --unhandled-rejections=strict create.js
    variables:
        TAG_PREFIX: "connectedfueling-app-"

create_empty_release:
  extends: .docker_image
  image: node:latest
  stage: release
  <<: *empty_release_schedule_rule
  script:
    - if $(eval $CONDITION); then echo "Releasing..."; else echo "Nothing to do"; exit 0; fi
    - echo "Current time to be used as new build and version number"
    - export BUILD_NUMBER=$(TZ=Etc/Utc date "+%Y%m%d%H")
    - export VERSION_NAME=$(TZ=Etc/Utc date "+%y.%V.%u")
    - export CUSTOM_TAG_NAME="${TAG_PREFIX}v${VERSION_NAME}.${BUILD_NUMBER}"
    - export EMPTY_RELEASE="true"
    - echo "Creating tag with tag name:" $CUSTOM_TAG_NAME
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/pace/mobile/common.git tmp/common
    - cd tmp/common/scripts/release
    - yarn install
    - node --unhandled-rejections=strict create.js
  variables:
    TAG_PREFIX: "connectedfueling-app-"

fetch_apps:
    extends: .docker_image
    image: python:3.8
    stage: apps
    <<: *tag_rule
    script:
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/pace/mobile/common.git tmp/common
        - pip3 install -r tmp/common/scripts/whitelabel-app/requirements.txt
        - python3 tmp/common/scripts/whitelabel-app/generate_build_apps_yaml.py --directus-base-url $DIRECTUS_BASE_URL --access-token=${DIRECTUS_ACCESS_TOKEN}
    artifacts:
        paths:
            - build-apps.yml

build_apps:
    stage: build
    <<: *tag_rule
    trigger:
        include:
            -   artifact: build-apps.yml
                job: fetch_apps
