object Versions {

    const val DEFAULT_VERSION_CODE_LIBRARY = 1
    const val DEFAULT_VERSION_NAME_LIBRARY = "13.1.1"

    const val COMPILE_SDK = 31
    const val TARGET_SDK = 31
    const val MIN_SDK = 23

    const val APPAUTH = "0.10.0"
    const val ANDROID_GRADLE_PLUGIN = "7.0.3"
    const val APPCOMPAT = "1.4.0-rc01"
    const val ARCH_TESTING = "2.1.0"
    const val BIOMETRIC = "1.1.0"
    const val BROWSER = "1.4.0"
    const val COMMONS_CODEC = "1.15"
    const val CONSTRAINT_LAYOUT = "2.1.1"
    const val CORE_KTX = "1.7.0"
    const val COROUTINES = "1.5.2"
    const val DOKKA = "1.5.30"
    const val FRAGMENT_KTX = "1.3.6"
    const val GOOGLE_MAPS_UTILS = "2.3.0"
    const val GOOGLE_PLAY_SERVICES_LOCATION = "18.0.0"
    const val GOOGLE_PLAY_SERVICES_MAPS = "18.0.0"
    const val GOOGLE_PROTOBUF_GRADLE_PLUGIN = "0.8.17"
    const val GOOGLE_PROTOBUF_JAVALITE = "3.19.1"
    const val GSON = "2.8.9"
    const val HILT = "2.38.1"
    const val JETPACK_COMPOSE = "1.1.1"
    const val JETPACK_COMPOSE_CONSTRAINT_LAYOUT = "1.0.0-beta02"
    const val KOIN = "3.1.3"
    const val KOTLIN = "1.6.10"
    const val LIFECYCLE_KTX = "2.4.0"
    const val MATERIAL_COMPONENTS = "1.6.0-alpha03"
    const val MOCKITO = "4.0.0"
    const val MOCKITO_KOTLIN = "4.0.0"
    const val MOCKK = "1.12.0"
    const val MOSHI_JSONAPI = "3.5.0"
    const val MOSHI_KOTLIN = "1.12.0"
    const val NAVIGATION = "2.4.1"
    const val NEXUS_STAGING = "0.30.0"
    const val OKHTTP = "4.9.2"
    const val ONE_TIME_PASSWORD = "2.1.0"
    const val PREFERENCE_KTX = "1.1.1"
    const val RECYCLER_VIEW = "1.2.1"
    const val RETROFIT = "2.9.0"
    const val ROBOLECTRIC = "4.6.1"
    const val ROOM = "2.4.0-beta02"
    const val RXANDROID = "3.0.0"
    const val RXJAVA = "3.1.2"
    const val TEST_CORE = "1.4.0"
    const val TEST_JUNIT = "1.1.3"
    const val TIMBER = "5.0.1"
}
